//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_Application
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Login_ApplicationEntities1 : DbContext
    {
        public Login_ApplicationEntities1()
            : base("name=Login_ApplicationEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<organization> organizations { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<DEVICE_INFO> DEVICE_INFO { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
    }
}
